swagger: "2.0"
info:
  description: "This is the API of the Istio BookInfo sample application."
  version: "1.0.0"
  title: "BookInfo Productpage"
  termsOfService: "https://istio.io/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1"
tags:
- name: "products"
  description: "Information about a product (in this case a book)"
externalDocs:
  description: "Learn more about the Istio BookInfo application"
  url: "https://istio.io/docs/samples/bookinfo.html"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "List all products"
      description: "List all products available in the application with a minimum amount of information."
      operationId: "getProducts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"

definitions:
  Product:
    type: "object"
    description: "Basic information about a product"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Product id"
      title:
        type: "string"
        description: "Title of the book"
      descriptionHtml:
        type: "string"
        description: "Description of the book - may contain HTML tags"
    required:
    - "id"
    - "title"
    - "descriptionHtml"
 